### PR TITLE
Fix #5 | allow something like "10-8" 

### LINKED ISSUE #5: Subtracting silver pices removes gold even when enough silver
In case your player has 11+ silver (treasure chest) and wants to subtract 10 you would loose one gp instead of the silver.

1 GP 11 Silver  | -10 Silver
0 GP 11 Silver  |

### PR DESCRIPTION
**Pull request by Nordiii**
Version 9.11 had issues when doing something like 80-81, this did not work correctly.

Also added simple logic to allow something like "10-8" instead of "-8" as I often double click and suddenly the input field is blank,

### CODE REVIEW

**Comment by Nordiii** [comment]
Just noticed there is still an error.

**Comment by DeVelox** [comment]
I'm sorry to keep you waiting, I appreciate the contribution with sign handling but the changes you made to removeMoney introduced some errors so I decided to keep my version of that function. On top of that I now ran into issues with the recursion so when I get around to fixing that I will push this and credit you in the changelog.

**Comment by Nordiii** [comment]
No problem you can just close this PR if you want to.

I noticed that with your branch doing something like
0 GP 20SP 0CP | -1GP

Would not work.

Also doing something like
1GP 80SP 0CP | - 90SP

would not work

**Comment by DeVelox** [comment]
Those are all related to the error I'm trying to figure out now. I will push your contribution and a fix for this as soon as I can.

**Comment by Nordiii** [comment]
Thanks for your work!

**Comment by DeVelox** [comment]
Ok, I pushed the update with your sign handling and my fixes for the subtraction. All of your examples and my own tests worked so hopefully no new bugs snuck in.

**Pull request closed without merging**
